"""Add appointments table

Revision ID: 38739a6dc12c
Revises: 63fbb9d953f7
Create Date: 2025-12-02 00:38:39.590700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38739a6dc12c'
down_revision = '63fbb9d953f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_name', sa.String(length=100), nullable=True),
    sa.Column('guest_email', sa.String(length=120), nullable=True),
    sa.Column('guest_phone', sa.String(length=20), nullable=True),
    sa.Column('appointment_type', sa.Enum('EYE_EXAM', 'FRAME_FITTING', 'CONTACT_LENS', 'CONSULTATION', name='appointmenttype'), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='appointmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    # ### end Alembic commands ###
